import { expect, test } from "@playwright/test";
const countries=[
 ["vietnam","vi","Học kỹ năng"],["philippines","fil","international business"],["tajikistan","tg","Hermes Academy"],["morocco","ar","Hermes Academy"],["moldova","ro","Hermes Academy"],["romania","ro","Hermes Academy"],
] as const;

test("four marketing package horizons are visible without stale fixed pricing",async({page})=>{await page.goto("/businesses/");const cards=page.locator("[data-marketing-packages] [data-package-months]");await expect(cards).toHaveCount(4);for(const m of [3,6,9,12])await expect(page.locator(`[data-package-months="${m}"]`)).toContainText(`${m} months`);await expect(page.locator("[data-marketing-packages]")).toContainText(/current fee are scoped after the business brief/i);await expect(page.locator("[data-marketing-packages]")).not.toContainText("$4,999");});

test("localized Academy launch pages expose four tracks, reciprocal language alternates and truthful gates",async({page})=>{for(const [slug,lang] of countries){await page.goto(`/academy/countries/${slug}/`);await expect(page.locator("html")).toHaveAttribute("lang",lang);await expect(page.locator("[data-country-track]")).toHaveCount(4);await expect(page.locator('link[rel="alternate"][hreflang="en"]')).toHaveAttribute("href",new RegExp(`/academy/countries/${slug}/en/$`));await expect(page.getByText(/not evidence of a Hermes office/i)).toBeVisible();await page.goto(`/academy/countries/${slug}/en/`);await expect(page.locator("html")).toHaveAttribute("lang","en");await expect(page.locator(`link[rel="alternate"][hreflang="${lang}"]`)).toHaveAttribute("href",new RegExp(`/academy/countries/${slug}/$`));}});

test("Catalog profile claim keeps identity in the on-site request handoff",async({page})=>{await page.goto("/businesses/arkansas/sherwood/seans-autopro-mobile/");const claim=page.getByRole("link",{name:"Request claim / verification"});await expect(claim).toHaveAttribute("href",/\/businesses\/request\/\?type=claim/);await claim.click();await expect(page.locator("[data-catalog-request]")).toHaveAttribute("data-request-type","claim");await expect(page.locator('input[name="company"]')).toHaveValue("Sean's AutoPro Mobile");await expect(page.locator("[data-connect-handoff]")).toHaveAttribute("href",/source=catalog_request/);});

test("Academy country application preserves country and interest pathway",async({page})=>{await page.goto("/academy/apply/?program=operations&country=Vietnam&language=en&source=academy_country");await expect(page.locator('select[name="academy_program"]')).toHaveValue("operations");await expect(page.locator('input[name="academy_country_city"]')).toHaveValue("Vietnam");});
