import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { onRequest, normalizeInput, parseAllowedPercentages } from "../functions/api/carrier-contract.ts";
import contractEmailWorker from "../workers/lead-email/src/index.mjs";

class MemoryKv { values=new Map(); async get(key){return this.values.get(key)??null;} async put(key,value){this.values.set(key,value);} }
const sha256=(bytes)=>createHash("sha256").update(bytes).digest("hex");
const approvedMaster=Buffer.from(`%PDF-1.4\n${"% Synthetic approved master document padding for attachment validation.\n".repeat(8)}1 0 obj << /Type /Catalog >> endobj\n%%EOF\n`,"utf8");
const approvedMasterSha=sha256(approvedMaster);
const signatureBytes=Buffer.alloc(900,17);const signatureData=`data:image/jpeg;base64,${signatureBytes.toString("base64")}`;
const serviceToken="test-contract-service-token-with-sufficient-length";const retiredRecipient="freight_301@hermeslogisticsus.com";const sentMessages=[];
const workerEnv={LEAD_SERVICE_TOKEN:serviceToken,SALES_DESTINATION:"officeus@hermeslogisticsus.com",SALES_SENDER:"website@hermeslogisticsus.com",CARRIER_CONTRACT_INTERNAL_RECIPIENTS:`officeus@hermeslogisticsus.com,${retiredRecipient},dispatch-test@hermeslogisticsus.com`,EMAIL:{async send(message){sentMessages.push(message);return{messageId:`contract-message-${sentMessages.length}`};}}};
const serviceCalls=[];const serviceBinding={async fetch(input,init){const request=input instanceof Request?input:new Request(input,init);const inspection=request.clone();serviceCalls.push({path:new URL(inspection.url).pathname,authorization:inspection.headers.get("Authorization"),payload:await inspection.json()});return contractEmailWorker.fetch(request,workerEnv);}};
const limits=new MemoryKv();
const env={ALLOWED_ORIGIN:"https://hermeslogisticsus.com",ASSETS:{async fetch(input){const url=new URL(input instanceof Request?input.url:String(input));assert.equal(url.pathname,"/contracts/test-approved-master.pdf");return new Response(approvedMaster,{status:200,headers:{"Content-Type":"application/pdf"}});}},LEAD_DELIVERY_MODE:"live",LEAD_SERVICE_TOKEN:serviceToken,LEAD_LIMITS:limits,LEAD_EMAIL_SERVICE:serviceBinding,CARRIER_CONTRACT_MODE:"live",CARRIER_CONTRACT_APPROVED_VERSION:"APPROVED-TEST-2026-08-06",CARRIER_CONTRACT_APPROVED_PDF_PATH:"/contracts/test-approved-master.pdf",CARRIER_CONTRACT_APPROVED_PDF_SHA256:approvedMasterSha,CARRIER_CONTRACT_ALLOWED_PERCENTAGES:"6, 8.00, 9.5"};
const validPayload={request_id:"contract_test_12345678",selected_plan:"pro",service_percentage:"8",custom_scope:"",legal_company_name:"TEST Hermes Carrier LLC",dba_name:"TEST Carrier",mc_number:"123456",usdot_number:"9876543",company_website:"https://carrier.example.com/about",signer_name:"Test Authorized Signer",signer_title:"Owner",signer_email:"carrier-test@example.com",signer_phone:"+1 414 555 0101",sales_contact:"TEST Assistant 34",offer_code:"PRO-AUG",typed_signature:"Test Authorized Signer",signature_jpeg:signatureData,signature_width:600,signature_height:180,consent_electronic_records:true,consent_authority:true,consent_document_review:true,consent_selected_scope:true,submitted_at:"2026-08-06T06:00:00.000Z"};
const contractRequest=(payload=validPayload,headers={})=>new Request("https://hermeslogisticsus.com/api/carrier-contract",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":String(payload.request_id??""),"Origin":"https://hermeslogisticsus.com","CF-Connecting-IP":"192.0.2.55","User-Agent":"Hermes synthetic contract test",...headers},body:JSON.stringify(payload)});

assert.deepEqual([...parseAllowedPercentages("6, 8.00; 9.5")],["6.00","8.00","9.50"]);
const normalized=normalizeInput(validPayload);assert.ok(normalized);assert.equal(normalized.planLabel,"Operations + Growth");assert.equal(normalized.percentage,"8%");assert.equal(normalized.percentageKey,"8.00");assert.equal(normalized.companyWebsite,"https://carrier.example.com/about");assert.equal(normalized.offerCode,"PRO-AUG");
const accepted=await onRequest({request:contractRequest(),env});assert.equal(accepted.status,200);assert.equal(accepted.headers.get("Content-Type"),"application/pdf");assert.equal(accepted.headers.get("X-Hermes-Delivery"),"delivered");assert.equal(accepted.headers.get("X-Hermes-Document-Mode"),"live");assert.match(accepted.headers.get("Content-Disposition")??"",/Hermes_TEST_Hermes_Carrier_LLC_Signed_Appendix_A\.pdf/);
const generatedPdf=Buffer.from(await accepted.arrayBuffer());assert.ok(generatedPdf.length>4_000);assert.equal(generatedPdf.subarray(0,8).toString("utf8"),"%PDF-1.4");assert.equal(accepted.headers.get("X-Hermes-Pdf-Sha256"),sha256(generatedPdf));assert.match(generatedPdf.toString("latin1"),/Hermes Carrier Agreement - Appendix A/);assert.match(generatedPdf.toString("latin1"),/Test Authorized Signer/);assert.match(generatedPdf.toString("latin1"),/Operations \+ Growth/);assert.match(generatedPdf.toString("latin1"),/8%/);assert.doesNotMatch(generatedPdf.toString("latin1"),/192\.0\.2\.55/);
assert.equal(serviceCalls.length,1);assert.equal(serviceCalls[0].path,"/v1/send-contract");assert.equal(serviceCalls[0].authorization,`Bearer ${serviceToken}`);assert.equal(serviceCalls[0].payload.subject,"[HERMES CONTRACT] [CARRIER ONBOARDING]");assert.equal(serviceCalls[0].payload.carrier_email,"carrier-test@example.com");assert.equal(serviceCalls[0].payload.attachments.length,2);const serialized=JSON.stringify(serviceCalls[0].payload);assert.match(serialized,/Carrier-specific percentage: 8%/);assert.match(serialized,/Website: https:\/\/carrier\.example\.com\/about/);assert.doesNotMatch(serialized,/"(?:password|passcode|pin|api[_-]?key|bank_account|routing_number)"\s*:/i);assert.doesNotMatch(serialized,/business_address|preferred_lanes|load_boards|access_handoff_method|192\.0\.2\.55/i);
assert.equal(sentMessages.length,3);assert.deepEqual(sentMessages.map((m)=>m.to).sort(),["carrier-test@example.com","dispatch-test@hermeslogisticsus.com","officeus@hermeslogisticsus.com"]);assert.ok(!sentMessages.some((m)=>m.to===retiredRecipient));
const fallbackRecipients=(await import("../workers/lead-email/src/index.mjs")).parseInternalRecipients({CARRIER_CONTRACT_INTERNAL_RECIPIENTS:retiredRecipient,SALES_DESTINATION:"officeus@hermeslogisticsus.com"});assert.deepEqual(fallbackRecipients,["officeus@hermeslogisticsus.com"]);
const duplicate=await onRequest({request:contractRequest(),env});assert.equal(duplicate.status,200);assert.equal(sentMessages.length,3);assert.equal(serviceCalls.length,1);
const forbidden=await onRequest({request:contractRequest({...validPayload,request_id:"contract_forbidden_12345",password:"must-never-be-accepted"},{"CF-Connecting-IP":"192.0.2.56"}),env:{...env,LEAD_LIMITS:new MemoryKv()}});assert.equal(forbidden.status,400);
for(const field of ["business_address","equipment_types","preferred_lanes","load_boards","access_handoff_method"]){assert.equal(normalizeInput({...validPayload,[field]:field==="equipment_types"||field==="load_boards"?["Legacy"]:"Legacy"}),null,`${field} must be rejected from the minimized pre-signature payload.`);}
const custom=normalizeInput({...validPayload,request_id:"contract_custom_123456",selected_plan:"custom",service_percentage:"7.25",custom_scope:"Hermes researches and negotiates within instructions; carrier retains final booking and all safety decisions."});assert.ok(custom);assert.equal(custom.percentage,"7.25% proposed - pending Hermes approval");
assert.equal(normalizeInput({...validPayload,typed_signature:"Someone Else"}),null);assert.equal(normalizeInput({...validPayload,mc_number:"",usdot_number:""}),null);assert.equal(normalizeInput({...validPayload,company_website:"javascript:alert(1)"}),null);
const disallowedEnv={...env,LEAD_LIMITS:new MemoryKv(),CARRIER_CONTRACT_ALLOWED_PERCENTAGES:"6,9.5"};const reviewResponse=await onRequest({request:contractRequest({...validPayload,request_id:"contract_rate_not_allowed"},{"CF-Connecting-IP":"192.0.2.57"}),env:disallowedEnv});assert.equal(reviewResponse.headers.get("X-Hermes-Document-Mode"),"review","A percentage absent from the production allowlist must fall back to review mode.");
const source=await (await import("node:fs/promises")).readFile(new URL("../functions/api/carrier-contract.ts",import.meta.url),"utf8");assert.match(source,/contract\.plan!=="custom"/);assert.match(source,/allowedPercentages\.has\(contract\.percentageKey\)/);assert.match(source,/master_document_hash_mismatch/);assert.doesNotMatch(source,/CARRIER_CONTRACT_INTERNAL_RECIPIENTS/);
for(const key of limits.values.keys())assert.doesNotMatch(key,/192\.0\.2\.55|contract_test_12345678|carrier-test@example\.com/);
console.log("Carrier contract v3 generation, allowed-rate gate, minimized pre-signature data, retired-recipient filtering, delivery, idempotency, and privacy tests passed.");
