import assert from 'node:assert/strict';
import fs from 'node:fs';
const read = (path) => fs.readFileSync(path, 'utf8');
const repairSchema = read('functions/api/_lib/repair-shop-schema.mjs');
const repairProfile = read('functions/api/repair-shop/profile.ts');
const catalogPublic = read('functions/api/_lib/catalog-public.mjs');
const catalogApi = read('functions/api/catalog/companies.ts');
const settings = read('src/pages/services/hermes-connect/repair-shops/settings.astro');
const request = read('src/pages/businesses/request/index.astro');
const catalogPage = read('src/pages/businesses/index.astro');
const dynamicProfile = read('functions/businesses/connect/[kind]/[slug].ts');
const sitemap = read('functions/sitemap-connect-catalog.xml.ts');
const reportEndpoint = read('functions/api/internal/catalog/monthly-seo-reports.ts');
const reportWorkflow = read('.github/workflows/hermes-catalog-monthly-seo-reports.yml');
const githubOidc = read('functions/api/_lib/github-oidc.mjs');

assert.match(repairSchema, /catalog_opt_in INTEGER NOT NULL DEFAULT 0/);
assert.match(repairSchema, /catalog_published_at/);
assert.match(repairSchema, /next_seo_report_at/);
assert.match(repairProfile, /typeof body\.catalog_opt_in === "boolean"/);
assert.match(repairProfile, /businesses\/connect\/repair-shop/);
assert.doesNotMatch(repairProfile, /hermes_company_profiles|load_board_access/);
assert.match(catalogPublic, /hermes_company_profiles/);
assert.match(catalogPublic, /repair_shops/);
assert.match(catalogPublic, /Owner-published · Hermes verification pending/);
assert.match(catalogPublic, /reportingCadence: "monthly"/);
assert.match(catalogApi, /listPublicCatalogEntries/);
assert.match(settings, /Publish my approved company details in Hermes Catalog/);
assert.match(settings, /6\+ months/);
assert.match(request, /Monthly growth budget/);
assert.match(request, /Done-for-you video \/ creator \/ actor content/);
assert.match(request, /Meta targeted ads/);
assert.match(catalogPage, /catalog-connect-live\.js/);
assert.match(dynamicProfile, /Customer records, appointments, private contacts and other CRM data are never published here/);
assert.match(sitemap, /listPublicCatalogEntries/);
assert.match(reportEndpoint, /verifyGitHubCatalogReportOidcToken/);
assert.match(reportEndpoint, /r\.catalog_opt_in = 1/);
assert.match(reportEndpoint, /next_seo_report_at <= \?/);
assert.match(reportEndpoint, /does not guarantee rankings, traffic, leads or revenue/);
assert.match(reportEndpoint, /SET next_seo_report_at = \?/);
assert.match(reportWorkflow, /hermes-catalog-monthly-seo-reports/);
assert.match(reportWorkflow, /id-token: write/);
assert.match(githubOidc, /CATALOG_REPORT_IDENTITY/);
console.log('catalog Connect growth contract: ok');
