import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const read = (path) => readFileSync(path, "utf8");
const schema = read("functions/api/_lib/repair-shop-schema.mjs");
const profile = read("functions/api/repair-shop/profile.ts");
const catalogOwnerApi = read("functions/api/repair-shop/catalog.ts");
const publicCatalogApi = read("functions/api/catalog/companies.ts");
const publicProfile = read("functions/businesses/connect/repair-shop/[slug].ts");
const catalogPage = read("src/pages/businesses/index.astro");
const loader = read("public/catalog-connect-live.v2.js");
const ownerPage = read("src/pages/services/hermes-connect/repair-shops/catalog.astro");
const robots = read("public/robots.txt");
const sitemapIndex = read("public/sitemapindex.xml");
const connectCatalogSitemap = read("functions/sitemap-connect-catalog.xml.ts");

assert.match(schema, /catalog_opt_in INTEGER NOT NULL DEFAULT 0/);
assert.match(schema, /next_seo_report_at/);
assert.match(profile, /typeof body\.catalog_opt_in === "boolean"/);
assert.doesNotMatch(profile, /hermes_company_profiles|load_board_access/);
assert.match(catalogOwnerApi, /sameOrigin\(request\)/);
assert.match(catalogOwnerApi, /catalog_opt_in=0,next_seo_report_at=NULL/);
assert.doesNotMatch(catalogOwnerApi, /load_board_access|hermes_company_profiles/);
assert.match(publicCatalogApi, /vertical_key='repair_shop'/);
assert.match(publicCatalogApi, /profileUrl: `\/businesses\/connect\/repair-shop\//);
assert.match(publicCatalogApi, /id: `repair-shop-crm:\${row\.id}`/);
assert.doesNotMatch(publicCatalogApi, /id: `repair-shop:\${row\.id}`/);
assert.doesNotMatch(publicCatalogApi, /\bphone\b|\bemail\b|client_name|appointment/);
assert.match(publicProfile, /No private customer records, appointments or account details appear on this page/);
assert.match(publicProfile, /does not indicate a Hermes customer relationship/);
assert.match(publicProfile, /type=claim&business=/);
assert.match(publicProfile, /type=catalog-growth&business=/);
assert.match(publicProfile, /catalog-business-request/);
assert.match(publicProfile, /repair-shop-crm:/);
assert.match(publicProfile, /Request contact via Hermes/);
assert.match(publicProfile, /indexing, rankings, or customer inquiries/);
assert.doesNotMatch(publicProfile, /the next scheduled checkpoint is/);
assert.match(publicProfile, /address_line1/);
assert.match(publicProfile, /postal_code/);
assert.match(publicProfile, /streetAddress/);
assert.match(publicProfile, /postalCode/);
assert.match(publicProfile, /areaServed/);
assert.match(publicProfile, /knowsAbout/);
assert.match(publicProfile, /openingHoursSpecification/);
assert.match(publicProfile, /OpeningHoursSpecification/);
assert.match(publicProfile, /Business hours/);
assert.match(publicProfile, /Auto Repair in/);
assert.match(publicProfile, /Services include/);
assert.match(publicProfile, /row\.phone|telephone/);
assert.doesNotMatch(publicProfile, /client_email|client_phone|client_name|vin|mileage/);
assert.match(catalogPage, /const cards = \(\) =>/);
assert.match(catalogPage, /hermes:catalog-profiles-loaded/);
assert.match(catalogPage, /catalog-connect-live\.v2\.js/);
assert.match(catalogPage, /data-catalog-business-count/);
assert.doesNotMatch(read("src/components/CatalogClientBenefit.astro"), /catalog-connect-live/);
assert.match(loader, /querySelectorAll\('\[data-catalog-business-count\]'\)/);
assert.match(loader, /grid\.querySelectorAll\('\[data-catalog-card\]'\)/);
assert.doesNotMatch(loader, /addEventListener\('input'|addEventListener\('submit'/);
assert.match(loader, /textContent = String\(company\.companyName/);
assert.match(ownerPage, /robots="noindex,nofollow"/);
assert.match(ownerPage, /6\+ months/);
assert.match(ownerPage, /No ranking, traffic or lead result is guaranteed/);
assert.match(robots, /Sitemap: https:\/\/hermeslogisticsus\.com\/sitemapindex\.xml/);
assert.doesNotMatch(robots, /Sitemap: https:\/\/hermeslogisticsus\.com\/sitemap-connect-catalog\.xml/);
assert.match(sitemapIndex, /https:\/\/hermeslogisticsus\.com\/sitemap-connect-catalog\.xml/);
assert.match(connectCatalogSitemap, /WHERE catalog_opt_in=1/);
assert.match(connectCatalogSitemap, /\/businesses\/connect\/repair-shop\/\$\{esc\(slug\)\}\//);
assert.doesNotMatch(connectCatalogSitemap, /client_email|client_phone|appointment|customer/);
const staticDealerProfile = read("src/pages/businesses/[state]/[city]/[slug].astro");
assert.match(staticDealerProfile, /class="catalog-profile-hero"/);
assert.match(staticDealerProfile, /\.catalog-profile-hero\{/);
assert.match(staticDealerProfile, /@media\(max-width:800px\)\{\.catalog-profile-hero/);
assert.doesNotMatch(staticDealerProfile, /class="hero"/);
assert.doesNotMatch(staticDealerProfile, /(?:^|[^-])\.hero\b/);
for (const [route, shopName] of [
  ["arkansas/little-rock/smart-bubble-mobile-auto-body-repair", "Smart Bubble Mobile Auto/Body Repair Shop"],
  ["arkansas/guy/clendenins-auto-repair", "Clendenin&#39;s Auto Repair"],
  ["arkansas/cedarville/the-dapper-wrench", "The Dapper Wrench"],
]) {
  const html = read(`dist/businesses/${route}/index.html`);
  assert.match(html, new RegExp(shopName.replaceAll("/", "\\/")));
  assert.match(html, /Unclaimed profile/);
  assert.match(html, /Not a Hermes customer/);
  assert.match(html, /Off until owner verification/);
  assert.match(html, /application\/ld\+json/);
  assert.match(html, /Website concept · Hermes preview/);
  assert.match(html, /Concept preview only/);
  assert.doesNotMatch(html, /hr@smartbubbleautorepair\.com|clintonautorepair@outlook\.com|hello@thedapperwrench\.com/);
}
const websiteConcept = read("src/components/CatalogWebsiteConcept.astro");
const catalogConceptRouteOwner = read("src/components/CatalogConceptRoute.astro");
const genericBusinessRoute = read("src/pages/businesses/[state]/[city]/[slug].astro");
const genericCountryRoute = read("src/pages/businesses/[state]/index.astro");
const genericLocalityRoute = read("src/pages/businesses/[state]/[city]/index.astro");
const conceptRouteRegistry = read("src/lib/catalog-concept-routes.ts");
const catalogConceptData = read("src/data/catalog-business-concepts.ts");
const catalogRequestHelper = read("src/lib/catalog-request.ts");
const catalogRequestPage = read("src/pages/businesses/request/index.astro");
const catalogLeadPayload = read("src/lib/catalog-lead-payload.mjs");
assert.match(catalogRequestHelper, /"catalog-business-request"/);
assert.match(catalogRequestHelper, /business_id/);
assert.match(catalogRequestHelper, /source_ref/);
assert.match(websiteConcept, /Request contact via Hermes/);
assert.match(websiteConcept, /data-default-locale/);
assert.match(websiteConcept, /data-uk/);
assert.match(websiteConcept, /data-en/);
assert.match(websiteConcept, /semanticCore/);
assert.match(websiteConcept, /business\.faq/);
assert.match(catalogConceptRouteOwner, /CatalogWebsiteConcept business=\{business\}/);
assert.match(catalogConceptRouteOwner, /defaultLocale="uk"/);
assert.doesNotMatch(catalogConceptRouteOwner, /data-lang|data-lead|form\?\.addEventListener/);
assert.match(conceptRouteRegistry, /catalogConceptCountryRoutes/);
assert.match(conceptRouteRegistry, /catalogConceptLocalityRoutes/);
assert.match(conceptRouteRegistry, /catalogConceptBusinessRoutes/);
assert.match(genericCountryRoute, /catalogConceptCountryRoutes/);
assert.match(genericLocalityRoute, /catalogConceptLocalityRoutes/);
assert.match(genericBusinessRoute, /catalogConceptBusinessRoutes/);
assert.match(genericBusinessRoute, /CatalogConceptRoute/);
for (const [page, expectedHref] of [
  ["dist/businesses/index.html", "/businesses/ukraine/"],
  ["dist/businesses/ukraine/index.html", "/businesses/ukraine/chaiky/"],
  ["dist/businesses/ukraine/index.html", "/businesses/ukraine/irpin/"],
  ["dist/businesses/ukraine/chaiky/index.html", "/businesses/ukraine/"],
  ["dist/businesses/ukraine/irpin/index.html", "/businesses/ukraine/"],
]) {
  assert.match(read(page), new RegExp(`href=["']${expectedHref.replaceAll("/", "\\/")}["']`));
}
assert.match(catalogConceptData, /localeCopy:/);
assert.match(catalogConceptData, /Телефон зламався\? Почніть із Чайка Store\./);
assert.match(catalogConceptData, /Phone problem\? Start with Chayka Store\./);
assert.match(catalogConceptData, /semanticCore:/);
assert.match(websiteConcept, /claim\/customer status changes only after verification/);
assert.match(websiteConcept, /Request a handoff to this business/);
assert.doesNotMatch(websiteConcept, />Contact this business\.</);
assert.match(catalogRequestPage, /catalog-business-request/);
assert.match(catalogRequestPage, /buildCatalogLeadContext/);
assert.match(catalogLeadPayload, /catalog_business_id/);
assert.match(catalogLeadPayload, /catalog_source_ref/);
assert.match(catalogLeadPayload, /utm_source/);
assert.match(catalogLeadPayload, /gclid/);
assert.match(catalogRequestPage, /external email delivery still requires a verified recipient path/);

const catalogEventApi = read("functions/api/catalog-business-event.ts");
const catalogEventSchema = read("functions/api/_lib/catalog-business-events.mjs");
const catalogTelemetry = read("public/catalog-business-telemetry.js");
const catalogReportApi = read("functions/api/repair-shop/catalog-report.ts");
const repairDashboard = read("src/pages/services/hermes-connect/repair-shops/dashboard.astro");
assert.match(staticDealerProfile, /data-catalog-event="call_click"/);
assert.match(staticDealerProfile, /data-catalog-event="request_start"/);
assert.match(staticDealerProfile, /maps_click/);
assert.match(staticDealerProfile, /hasMap/);
assert.match(publicProfile, /data-catalog-event="booking_start"/);
assert.match(publicProfile, /data-catalog-event="request_start"/);
assert.match(publicProfile, /catalog-business-telemetry\.js/);
assert.match(catalogEventSchema, /PRIMARY KEY\(day, catalog_business_id, event_type\)/);
assert.match(catalogEventSchema, /"profile_view"/);
assert.match(catalogEventSchema, /"call_click"/);
assert.match(catalogEventApi, /analytics_consent_required/);
assert.match(catalogEventApi, /sameOriginRequest/);
assert.doesNotMatch(catalogEventApi, /CF-Connecting-IP|userAgent|visitor_id|client_email|contact_email/);
assert.match(catalogTelemetry, /hermes-analytics-consent/);
assert.match(catalogTelemetry, /navigator\.webdriver/);
assert.doesNotMatch(catalogTelemetry, /document\.cookie|localStorage\.setItem|fingerprint/);
assert.match(catalogReportApi, /days: 7/);
assert.match(catalogReportApi, /consented_profile_views/);
assert.match(catalogReportApi, /crm_inquiries/);
assert.match(catalogReportApi, /crm_bookings_created_all_sources/);
assert.match(catalogReportApi, /does not yet prove every booking originated from Catalog/);
assert.match(repairDashboard, /7-day Catalog report/);
assert.match(repairDashboard, /Consented profile views/);
assert.match(repairDashboard, /CRM bookings · all sources/);
assert.match(repairDashboard, /catalog-email-notifications/);
assert.match(repairDashboard, /Email me Catalog inquiries and weekly reports/);
assert.match(schema, /catalog_email_notifications_opt_in INTEGER NOT NULL DEFAULT 0/);
assert.match(schema, /\+7 days/);
assert.match(profile, /reporting_cadence: listed \? "weekly"/);
assert.match(ownerPage, /Reporting is scheduled weekly/);

const weeklyReportApi = read("functions/api/internal/reports/catalog-weekly.ts");
const weeklyWorkflow = read(".github/workflows/hermes-connect-weekly-inactivity-reminders.yml");
const leadEmailWorker = read("workers/lead-email/src/index.mjs");
const inquirySchema = read("functions/api/_lib/catalog-business-inquiries.mjs");
assert.match(weeklyReportApi, /verifyGitHubReminderOidcToken/);
assert.match(weeklyReportApi, /catalog_email_notifications_opt_in = 1/);
assert.match(weeklyReportApi, /catalog_weekly_report_deliveries/);
assert.match(weeklyReportApi, /\[HERMES CATALOG\] \[WEEKLY REPORT\]/);
assert.match(weeklyReportApi, /\[HERMES CATALOG\] \[WEEKLY REPORT INTERNAL\]/);
assert.match(weeklyReportApi, /Call button clicks/);
assert.match(weeklyReportApi, /not a completed phone conversation/);
assert.match(weeklyReportApi, /next_seo_report_at = \?/);
assert.match(weeklyWorkflow, /CATALOG_REPORT_URL/);
assert.match(weeklyWorkflow, /Deliver due Catalog weekly reports/);
assert.match(leadEmailWorker, /\[HERMES CATALOG\] \[CUSTOMER INQUIRY\]/);
assert.match(leadEmailWorker, /\[HERMES CATALOG\] \[WEEKLY REPORT\]/);
assert.match(leadEmailWorker, /\[HERMES CATALOG\] \[WEEKLY REPORT INTERNAL\]/);
assert.match(inquirySchema, /owner_delivery_status/);
assert.match(inquirySchema, /owner_delivery_at/);
console.log("Catalog Connect publication contract OK");
