import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
const route = "/insights/technology/i-am-vision/";
const url = `https://hermeslogisticsus.com${route}`;
const html = await readFile(new URL(`../dist${route}index.html`, import.meta.url), "utf8");
const main = html.match(/<main\b[^>]*>([\s\S]*?)<\/main>/)?.[1];
assert.ok(main, "Article main must be present");
assert.doesNotMatch(main, /\bhref\s*=\s*["']mailto:/i, "Article must not render a partnership/investor email CTA");
assert.match(html, /<a[^>]*href="mailto:officeus@hermeslogisticsus\.com"/, "Standard company footer email remains available");
assert.doesNotMatch(main, /Hermes is exploring conversations with technology partners/);
assert.match(main, /conditional research topics/);
assert.match(main, /This article does not open a partnership or investor inquiry process/);
assert.doesNotMatch(html, /start an exploratory email conversation|Prospective partners may/);
assert.match(html, /This editorial announcement documents the proposed development journey and its current boundaries/);
assert.equal((html.match(/<h1\b/g) || []).length, 1);
assert.match(html, /<link[^>]*rel="canonical"[^>]*href="https:\/\/hermeslogisticsus\.com\/insights\/technology\/i-am-vision\/"/);
assert.match(html, /<meta[^>]*name="robots"[^>]*content="index,follow,max-image-preview:large"/);
const schemas = [...html.matchAll(/<script\b[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/g)].flatMap(match => {
  const data = JSON.parse(match[1]);
  return Array.isArray(data) ? data : [data];
});
assert.ok(schemas.some(schema => schema["@type"] === "NewsArticle" && schema.mainEntityOfPage === url));
assert.ok(schemas.some(schema => schema["@type"] === "BreadcrumbList" && schema.itemListElement?.some(item => item.position === 3 && item.item === url)));
assert.ok(html.includes('href="/businesses/"'));
assert.ok(html.includes('href="/services/hermes-connect/"'));
const rss = await readFile(new URL("../dist/insights/rss.xml", import.meta.url), "utf8");
const sitemap = await readFile(new URL("../dist/sitemap-insights.xml", import.meta.url), "utf8");
assert.ok(rss.includes(url));
assert.equal(sitemap.split(url).length - 1, 1, "Existing sitemap owner must remain singular");
const generic = await readFile(new URL("../dist/paths/technology/index.html", import.meta.url), "utf8");
assert.match(generic, /<a[^>]*href="mailto:officeus@hermeslogisticsus\.com"/, "Other routes retain the default direct email footer");
console.log("I am editorial-only article, no lead mailto CTA, standard footer preserved, singular canonical/NewsArticle/sitemap/RSS and default footer contract PASS");
