import assert from 'node:assert/strict';
import {test} from 'node:test';
import {Miniflare} from './helpers/knb-sqlite-d1.mjs';
import {ensureHermesCompanyProfilesSchema} from '../functions/api/_lib/hermes-company-profiles.mjs';
import {provisionKnbCompany} from '../functions/api/_lib/client-company-provisioning.mjs';
const input={client_owner_id:'synthetic-client',client_identity_confirmed:true,companyName:'Конс на Бі$',companyType:'business_club',countryCode:'UA',city:'Synthetic city',region:'Synthetic region',website:'https://biznes-club-knb.com/'};
async function setup(){const mf=new Miniflare(),db=await mf.getD1Database();await db.prepare('CREATE TABLE specialists(id TEXT PRIMARY KEY)').run();await db.prepare("INSERT INTO specialists(id) VALUES('synthetic-client')").run();await ensureHermesCompanyProfilesSchema(db);return {mf,db};}
function injectDeletion(db,stage){const prepare=db.prepare.bind(db);let fired=false;db.prepare=sql=>{const q=prepare(sql);const method=stage==='before-insert'&&sql.includes('INSERT OR IGNORE INTO hermes_company_profiles')?'run':stage==='before-replay-read'&&sql.includes('FROM hermes_company_profiles')&&sql.includes('slug,company_type')&&sql.startsWith('SELECT')?'all':stage==='before-final-read'&&sql.includes('FROM hermes_company_profiles WHERE id=?')?'first':null;if(method){const original=q[method].bind(q);q[method]=async()=>{if(!fired){fired=true;await prepare("DELETE FROM specialists WHERE id='synthetic-client'").run();}return original();};}return q;};return {prepare,fired:()=>fired};}
test('review counterexample: identity deleted before INSERT cannot create orphan/success',async()=>{const {mf,db}=await setup();try{const hook=injectDeletion(db,'before-insert');const r=await provisionKnbCompany(db,'synthetic-operator',input);const identities=(await hook.prepare('SELECT COUNT(*) AS n FROM specialists').first()).n,companies=(await hook.prepare('SELECT COUNT(*) AS n FROM hermes_company_profiles').first()).n;console.log(JSON.stringify({scenario:'before-insert',status:r.status,success:r.body.success,identities,companies}));assert.equal(hook.fired(),true);assert.equal(identities,0);assert.equal(companies,0);assert.equal(r.body.success,false);assert.ok(r.status>=400);}finally{await mf.dispose();}});
test('identity removed before existing-company read cannot receive orphan replay success',async()=>{const {mf,db}=await setup();try{assert.equal((await provisionKnbCompany(db,'synthetic-operator',input)).status,201);const hook=injectDeletion(db,'before-replay-read');const r=await provisionKnbCompany(db,'synthetic-operator',input);console.log(JSON.stringify({scenario:'before-replay-read',status:r.status,success:r.body.success}));assert.equal(hook.fired(),true);assert.equal(r.body.success,false);assert.ok(r.status>=400);assert.equal((await hook.prepare('SELECT COUNT(*) AS n FROM hermes_company_profiles').first()).n,1);}finally{await mf.dispose();}});
test('identity removed after INSERT is excluded from final success receipt, without deleting company data',async()=>{const {mf,db}=await setup();try{const hook=injectDeletion(db,'before-final-read');const r=await provisionKnbCompany(db,'synthetic-operator',input);console.log(JSON.stringify({scenario:'before-final-read',status:r.status,success:r.body.success}));assert.equal(hook.fired(),true);assert.equal(r.body.success,false);assert.ok(r.status>=400);assert.equal((await hook.prepare('SELECT COUNT(*) AS n FROM hermes_company_profiles').first()).n,1);}finally{await mf.dispose();}});
