import assert from 'node:assert/strict';
import {test} from 'node:test';
import {createRequire} from 'node:module';
import {ensureHermesCompanyProfilesSchema} from '../functions/api/_lib/hermes-company-profiles.mjs';
import {provisionKnbCompany} from '../functions/api/_lib/client-company-provisioning.mjs';
import {publicCompanyFacts} from '../functions/api/_lib/public-company-facts.mjs';
const {Miniflare}=await import('./helpers/knb-sqlite-d1.mjs');
const fixture={client_owner_id:'synthetic-client-a',client_identity_confirmed:true,companyName:'Конс на Бі$',companyType:'business_club',countryCode:'UA',city:'Синтетичне місто',region:'Синтетична область',website:'https://biznes-club-knb.com/zrostannia-u-biznesi-ads'};
async function setup(){const mf=new Miniflare({modules:true,script:'export default {fetch(){return new Response("local-only")}}',compatibilityDate:'2026-07-30',d1Databases:{DB:'synthetic-knb-company'},d1Persist:false});const db=await mf.getD1Database('DB');await db.prepare('CREATE TABLE specialists(id TEXT PRIMARY KEY)').run();await db.batch(['synthetic-client-a','synthetic-client-b','synthetic-operator'].map(id=>db.prepare('INSERT INTO specialists(id) VALUES(?)').bind(id)));await ensureHermesCompanyProfilesSchema(db);return{mf,db};}
const run=(name,fn)=>test(name,async()=>{const {mf,db}=await setup();try{await fn(db);}finally{await mf.dispose();}});
run('creates canonical client-owned UA club with modules/publication off; no identity/schema changes',async db=>{
 const before=(await db.prepare('SELECT name,sql FROM sqlite_master ORDER BY name').all()).results;const r=await provisionKnbCompany(db,'synthetic-operator',{...fixture,owner_specialist_id:'synthetic-operator',loadBoardAccess:true,catalogOptIn:true});assert.equal(r.status,201);assert.equal(r.body.company.countryCode,'UA');assert.equal(r.body.company.state,fixture.region);assert.equal(r.body.company.loadBoardAccess,false);assert.equal(r.body.company.catalogOptIn,false);const row=await db.prepare('SELECT * FROM hermes_company_profiles').first();assert.equal(row.owner_specialist_id,fixture.client_owner_id);assert.equal(row.website,'https://biznes-club-knb.com/');assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM specialists').first()).n,3);assert.deepEqual((await db.prepare('SELECT name,sql FROM sqlite_master ORDER BY name').all()).results,before);assert.match(r.body.readback_path,/^\/api\/internal\/client-company\?company_id=/);
});
run('same facts return one existing company without update',async db=>{const a=await provisionKnbCompany(db,'synthetic-operator',fixture);const before=await db.prepare('SELECT * FROM hermes_company_profiles').first();const b=await provisionKnbCompany(db,'synthetic-operator',fixture);assert.equal(b.status,200);assert.equal(b.body.company_id,a.body.company_id);assert.equal(b.body.duplicate,true);assert.deepEqual(await db.prepare('SELECT * FROM hermes_company_profiles').first(),before);});
run('operator identity cannot be substituted as client',async db=>{const r=await provisionKnbCompany(db,'synthetic-operator',{...fixture,client_owner_id:'synthetic-operator'});assert.equal(r.status,400);assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM hermes_company_profiles').first()).n,0);});
run('existing selected identity and explicit confirmation required',async db=>{assert.equal((await provisionKnbCompany(db,'synthetic-operator',{...fixture,client_identity_confirmed:false})).status,400);assert.equal((await provisionKnbCompany(db,'synthetic-operator',{...fixture,client_owner_id:'synthetic-missing'})).status,404);});
run('refuses replacing an unrelated existing company',async db=>{await db.prepare("INSERT INTO hermes_company_profiles(id,owner_specialist_id,company_name,slug,company_type,city,state,website,catalog_opt_in,catalog_status,load_board_access,created_at,updated_at) VALUES('synthetic-other','synthetic-client-a','Other company','other','dealer','Test','IL','https://example.com/',1,'verified_public',1,'before','before')").run();const before=await db.prepare('SELECT * FROM hermes_company_profiles').first();assert.equal((await provisionKnbCompany(db,'synthetic-operator',fixture)).status,409);assert.deepEqual(await db.prepare('SELECT * FROM hermes_company_profiles').first(),before);});
run('official domain dedupes another owner across www/path forms',async db=>{await db.prepare("INSERT INTO hermes_company_profiles(id,owner_specialist_id,company_name,slug,company_type,city,state,website,catalog_opt_in,catalog_status,load_board_access,created_at,updated_at) VALUES('synthetic-linked','synthetic-client-b','Existing KNB','knb','other','Test','IL','https://www.biznes-club-knb.com/policies',0,'self_submitted',0,'before','before')").run();assert.equal((await provisionKnbCompany(db,'synthetic-operator',fixture)).status,409);assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM hermes_company_profiles').first()).n,1);});
run('company name dedupes without relying on a website',async db=>{await db.prepare("INSERT INTO hermes_company_profiles(id,owner_specialist_id,company_name,slug,company_type,city,state,catalog_opt_in,catalog_status,load_board_access,created_at,updated_at) VALUES('synthetic-name','synthetic-client-b',?,'knb','other','Test','IL',0,'self_submitted',0,'before','before')").bind('конс на бі$').run();assert.equal((await provisionKnbCompany(db,'synthetic-operator',fixture)).status,409);});
run('concurrent identical calls create only one company',async db=>{const r=await Promise.all([provisionKnbCompany(db,'synthetic-operator',fixture),provisionKnbCompany(db,'synthetic-operator',fixture)]);assert.equal(r.filter(x=>x.status===201).length,1);assert.equal(r.filter(x=>x.status===200).length,1);assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM hermes_company_profiles').first()).n,1);});
run('concurrent different owner calls conflict rather than rebind',async db=>{const r=await Promise.all([provisionKnbCompany(db,'synthetic-operator',fixture),provisionKnbCompany(db,'synthetic-operator',{...fixture,client_owner_id:'synthetic-client-b'})]);assert.equal(r.filter(x=>x.status===201).length,1);assert.equal(r.filter(x=>x.status===409).length,1);assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM hermes_company_profiles').first()).n,1);});
run('concurrent changed location cannot falsely report duplicate acceptance',async db=>{const r=await Promise.all([provisionKnbCompany(db,'synthetic-operator',fixture),provisionKnbCompany(db,'synthetic-operator',{...fixture,city:'Other synthetic city'})]);assert.equal(r.filter(x=>x.status===201).length,1);assert.equal(r.filter(x=>x.status===409).length,1);});
run('unsupported inputs/missing geography fail without writes',async db=>{for(const update of [{countryCode:'US'},{companyType:'repair_shop'},{city:''},{website:'https://biznes-club-knb.com.evil.example/'},{website:'https://user:pass@biznes-club-knb.com/'}])assert.equal((await provisionKnbCompany(db,'synthetic-operator',{...fixture,...update})).status,400);assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM hermes_company_profiles').first()).n,0);});
test('missing schema fails closed without migration',async()=>{const mf=new Miniflare({modules:true,script:'export default {}',compatibilityDate:'2026-07-30',d1Databases:{DB:'synthetic-empty'},d1Persist:false});try{const db=await mf.getD1Database('DB');assert.equal((await provisionKnbCompany(db,'synthetic-operator',fixture)).body.error,'canonical_company_schema_not_ready');assert.equal((await db.prepare("SELECT COUNT(*) AS n FROM sqlite_master WHERE type='table' AND name='hermes_company_profiles'").first()).n,0);}finally{await mf.dispose();}});
test('public projection excludes all private ownership/contact/inquiry/budget fields',()=>{const row={id:'synthetic-company',company_name:'Конс на Бі$',company_type:'business_club',country_code:'UA',city:'Test',state:'Test',catalog_status:'self_submitted',owner_specialist_id:'private-owner',phone:'private-phone',email:'private-email',monthly_amount:100,currency:'USD',goals:'private-goals',internal_notes:'private-notes',delivery_payload_json:'private-payload'};const projected=publicCompanyFacts(row);assert.equal(projected.countryCode,'UA');assert.equal(projected.profileUrl,null);for(const key of ['owner_specialist_id','phone','email','monthly_amount','currency','goals','internal_notes','delivery_payload_json'])assert.equal(key in projected,false);});
