/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false ./src/worker-configuration.d.ts` (hash: f9c5e786ea13e26b2f51ca5ea23ab04a)
interface __BaseEnv_Env {
	ALLOWED_ORIGIN: "https://hermeslogisticsus.com";
	SALES_DESTINATION: "officeus@hermeslogisticsus.com";
	SALES_SENDER: "website@hermeslogisticsus.com";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
